name: Send survey to Telegram

on:
  repository_dispatch:
    types: [survey]

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Send message
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TG_TOKEN }}/sendMessage" \
          -d chat_id=${{ secrets.TG_CHAT }} \
          -d text="üß™ –¢–ï–°–¢–û–í–û–ï –°–û–û–ë–©–ï–ù–ò–ï. GitHub Actions —Ä–∞–±–æ—Ç–∞–µ—Ç."
