name: Send survey to Telegram

on:
  repository_dispatch:
    types: [survey]

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Telegram
        run: |
          TEXT="üìù –ù–æ–≤—ã–π –æ–ø—Ä–æ—Å: Roblox\n\n‚ûï –ü–æ–ª–æ–∂–∏—Ç–µ–ª—å–Ω–æ–µ:\n${{ github.event.client_payload.positive }}\n\n‚ûñ –û—Ç—Ä–∏—Ü–∞—Ç–µ–ª—å–Ω–æ–µ:\n${{ github.event.client_payload.negative }}"
          curl -X POST "https://api.telegram.org/bot${{ secrets.TG_TOKEN }}/sendMessage" \
            -d chat_id=${{ secrets.TG_CHAT }} \
            --data-urlencode text="$TEXT"
