name: Send survey to Telegram

on:
  repository_dispatch:
    types: [survey]

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Send message
        run: |
          TEXT="üìù –ù–æ–≤—ã–π –æ–ø—Ä–æ—Å: Roblox

‚ûï –ü–æ–ª–æ–∂–∏—Ç–µ–ª—å–Ω–æ–µ:
${{ github.event.client_payload.positive }}

‚ûñ –û—Ç—Ä–∏—Ü–∞—Ç–µ–ª—å–Ω–æ–µ:
${{ github.event.client_payload.negative }}"

          curl -X POST https://api.telegram.org/bot${{ secrets.TG_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TG_CHAT }} \
          -d text="$TEXT"
